using System;
using System.Text;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using NReco.PdfGenerator;
using System.Configuration;
using System.Net.NetworkInformation;

public partial class TestPDF : System.Web.UI.Page
{

    StringBuilder TBL = new StringBuilder();
    StringBuilder Head = new StringBuilder();
    HtmlGenericControl div = new HtmlGenericControl();
    protected void Page_Load(object sender, EventArgs e)
    {

    }
    protected void btnGenertePDf_Click(object sender, EventArgs e)
    {
        string LogoPath = System.Configuration.ConfigurationManager.AppSettings["LogoPath"];
        string ChartImagePath = System.Configuration.ConfigurationManager.AppSettings["ChartImagePath"];
        TBL.Append("<section class=\"bannerarea\">");
        TBL.Append("<div class=\"container\">");
        TBL.Append("<div style=\"margin-bottom:12px;margin-left: 390px;\">");
        TBL.Append("<img src=\"" + LogoPath + "\"/>");
        TBL.Append("</div>");

        TBL.Append("<table style = \"width:100%;border-collapse: collapse;font-family: 'Roboto', sans-serif;font-size:13px;border:1px solid #d5d5d5;background:#fff;margin-bottom:.65cm;\">");

        TBL.Append("<tr>");

        TBL.Append("<td style = \"text-align:left;padding:.30cm;border-bottom:1px solid #d5d5d5;\" >");
        TBL.Append("<div style = \"font-size: 20px;font-weight:bold;color:#f25e0a;\" >Deepak Kumar Nirwal</div>");
        TBL.Append("<div style = \"font-size: 14px;color:#000;\" > 10 - Nov - 2019 at 04:34 PM(Uttar Pradesh, India)</div >");
        TBL.Append("</td>");

        TBL.Append("<td style = \"text-align:right;padding:.30cm;border-bottom:1px solid #d5d5d5;\">");
        TBL.Append("<div style = \"font-size: 20px;font-weight:bold;color:#000;\">Your Report On</div>");
        TBL.Append("<div style = \"font -size: 14px;color:#000;\" >Career & Profession</div>");
        TBL.Append("</td>");

        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.30cm;border-right:1px solid #d5d5d5;vertical-align:top;\" >");
        TBL.Append("<table style =\"border-collapse:collapse;\">");

        TBL.Append("<tr>");

        TBL.Append("<td><strong>Client Name</strong > </td>");
        TBL.Append("<td>:Deepak Kumar Nirwal </td>");

        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong> Gender </strong > </td>");
        TBL.Append("<td>:Male</td>");

        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong> Date of Birth</strong></td>");
        TBL.Append("<td>:10-Nov-1987</td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Time of Birth</strong ></td>");
        TBL.Append("<td>: 02:14 PM </td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Place of Birth</strong></td>");
        TBL.Append("<td>: Muzaffarnagar</td >");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Day of Birth</strong ></td>");
        TBL.Append("<td>:Sunday</td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>State</strong></td>");
        TBL.Append("<td>: Uttar Pradesh</td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Country</strong></td>");
        TBL.Append("<td>: India </td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong> Email </strong ></td>");
        TBL.Append("<td>: deepaknirwal@gmail.com </td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong> Contact No.</strong> </td>");
        TBL.Append("<td>: +91 - 9953248136 </td>");
        TBL.Append("</tr>");

        TBL.Append("</table>");

        TBL.Append("</td>");

        TBL.Append("<td style = \"padding:.30cm;vertical-align:top;\">");

        TBL.Append("<table style = \"border-collapse: collapse;\">");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Latitude</strong></td>");
        TBL.Append("<td>:22.34465756 </td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Longitude</strong></td>");
        TBL.Append("<td>:77.65454</td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Time Zone</strong></td>");
        TBL.Append("<td>: 5:30 </td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Constellation</strong></td>");
        TBL.Append("<td>: Revati</td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Rashi</strong></td>");
        TBL.Append("<td>: Pisces</td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong> Balance Dasha </strong> </td>");
        TBL.Append("<td>: Mercury Dasha 0 Years 8 Months 0 Days </td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Sunrise Time</strong></td>");
        TBL.Append("<td>: 10-Nov-2019, 06:38:30 AM</td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Sunset Time</strong></td>");
        TBL.Append("<td>: 10-Nov-2019, 05:27:30 PM </td >");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong>Next Day Sunrise Time </strong></td>");
        TBL.Append("<td>: 11-Nov-2019, 06:39:30 AM </td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong> Day Duration / Dinmaan </strong></td>");
        TBL.Append("<td>: 10:48:45 </td>");
        TBL.Append("</tr>");

        TBL.Append("<tr>");
        TBL.Append("<td><strong> Night Duration / Ratrimaan </strong></td>");
        TBL.Append("<td>: 13:12:02 </td>");
        TBL.Append("</tr>");

        TBL.Append("</table>");
        TBL.Append("</td>");
        TBL.Append("</tr>");
        TBL.Append("</table>");



        TBL.Append("<table style = \"width:100%;border-collapse: collapse;font-family: 'Roboto', sans-serif;font-size:13px;margin-bottom:.65cm;-webkit-print-color-adjust: exact;\">");
        TBL.Append("<tr>");
        TBL.Append("<td colspan = \"2\" style = \"text-align:left;padding:.30cm 0;\">");
        TBL.Append("<div style = \"font-size: 20px;font-weight:bold;color:#f25e0a;\" > Birth Chart </div>");
        TBL.Append("</td>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"vertical-align:top; \">");
        TBL.Append("<table style = \"width:100%;border-collapse: collapse;\">");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;background:#555;color:#fff;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\"> Planets </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;background:#555;color:#fff;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Rashi </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;background:#555;color:#fff;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > House </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;background:#555;color:#fff;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Degree </td> ");
        TBL.Append("<td style = \"padding:.1cm .2cm;background:#555;color:#fff;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Minutes </td> ");
        TBL.Append("<td style = \"padding:.1cm .2cm;background:#555;color:#fff;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Seconds </td> ");
        TBL.Append("<td style = \"padding:.1cm .2cm;background:#555;color:#fff;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Retro </td> ");
        TBL.Append("<td style = \"padding:.1cm .2cm;background:#555;border-right:1px solid #d5d5d5;color:#fff;-webkit-print-color-adjust: exact;\" > Const </th> ");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > ASCENDENT </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\"> Aries </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\"> House1 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\"> 01 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\"> 22 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\"> 54 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\"> -</td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-top:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\"> Ashwini </th>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > SUN </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Libra </td>");
        TBL.Append("<td style =\"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > House7 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 23 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 22 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 54 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > -</td>");
        TBL.Append(" <td style = \"padding:.1cm .2cm;border-top:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Vishakha </th>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > MOON </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Pisces </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > House12 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 23 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 22 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 54 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > -</td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-top:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Revati </th>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > MARS </ td >");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Libra </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > House7 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 23 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 22 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 54 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > -</td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-top:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Chitra </th>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > MERCURY </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Libra </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > House7 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 23 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 22 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 54 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > DC </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-top:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Vishakha </th>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\"> JUPITER </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Sagittarius </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > House9 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 23 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 22 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 54 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > -</td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-top:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Moola </th>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > VENUS </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Scorpio </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > House8 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 23 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 22 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 54 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > -</td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-top:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Anuradha </th>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > SATURN </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Sagittarius </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > House9 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 23 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 22 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 54 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > -</td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-top:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Poorva Ashadha </th>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > RAHU </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Gemini </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > House3 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 23 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 22 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 54 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > -</td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-top:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Ardra </th>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > KETU </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Sagittarius </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > House9 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 23 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 22 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 54 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > -</td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-top:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Poorva Ashadha </th>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-left:1px solid #d5d5d5;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;border-bottom:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > GULIKA </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;border-bottom:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Pisces </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;border-bottom:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > House12 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;border-bottom:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 23 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;border-bottom:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 22 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;border-bottom:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > 54 </td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-right:1px solid #d5d5d5;border-top:1px solid #d5d5d5;border-bottom:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > -</td>");
        TBL.Append("<td style = \"padding:.1cm .2cm;border-top:1px solid #d5d5d5;border-bottom:1px solid #d5d5d5;border-right:1px solid #d5d5d5;-webkit-print-color-adjust: exact;\" > Revati </th>");
        TBL.Append("</tr>");
        TBL.Append("</table>");

        TBL.Append("</td>");
        TBL.Append("<td style = \"padding:.0cm;vertical-align:top;width:425px;\">");
        TBL.Append("<div style = \"background:url(" + ChartImagePath + ") no-repeat;background-position: center;background-size: 100% 100%;-webkit-print-color-adjust: exact;position: relative;z-index: 1;display: block;width:418px;margin-left:6px; padding-top: 100%;\">");
        TBL.Append("<div style=\"position:absolute; top:20%;  left:40%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h1l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\" >Ra<span style =\"text-align:left; color:#F4600A; font-size:12px;font-weight: bold;\"></span> <span style=\"text-align:left; color:#F4600A; font-size:11px;font-weight: bold;\">20.08</span> Asc<span style=\"text-align:left; color:#F4600A; font-size:11px;font-weight: bold;\">10.06</span></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:20%;  left:40%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h1r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">11</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top: 3%;  left: 14%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h2l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ma<span style=\"text-align:left; color:#F4600A; font-size:12px;font-weight: bold;\">R</span> <span style=\"text-align:left; color:#F4600A; font-size:11px;font-weight: bold;\">10.33</span> </span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top: 13%;  left: 24%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h2r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">12</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:20%; left:2%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h3l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:19%; left:19%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h3r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">1</span><br></span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:42%; left:15%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"h4l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Mo<span style=\"text-align:left; color:#F4600A; font-size:12px;font-weight: bold;\"></span> <span style=\"text-align:left; color:#F4600A; font-size:11px;font-weight: bold;\">29.52</span> Ju<span style=\"text-align:left; color:#F4600A; font-size:12px;font-weight: bold;\">R</span> <span style=\"text-align:left; color:#F4600A; font-size:11px;font-weight: bold;\">12.20</span> </span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:43%; left:44%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h4r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">2</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:70%; left:2%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h5l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:67%; left:17%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h5r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">3</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:87%; left:14%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h6l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:73%; left:25%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h6r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">4</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:70%; left:40%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h7l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ve<span style=\"text-align:left; color:#F4600A; font-size:12px;font-weight: bold;\"></span> <span style=\"text-align:left; color:#F4600A; font-size:11px;font-weight: bold;\">02.44</span> Ke<span style=\"text-align:left; color:#F4600A; font-size:12px;font-weight: bold;\"></span> <span style=\"text-align:left; color:#F4600A; font-size:11px;font-weight: bold;\">20.08</span> </span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:49%; left:49%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h7r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">5</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:87%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h8l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Su<span style=\"text-align:left; color:#F4600A; font-size:12px;font-weight: bold;\"></span> <span style=\"text-align:left; color:#F4600A; font-size:11px;font-weight: bold;\">14.46</span> Gk<span style=\"text-align:left; color:#F4600A; font-size:12px;font-weight: bold;\"></span> <span style=\"text-align:left; color:#F4600A; font-size:11px;font-weight: bold;\">24.06</span> </span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:73%; left:74%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"h8r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">6</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:67%; left:85%;width:15%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"h9l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Me<span style=\"text-align:left; color:#F4600A; font-size:12px;font-weight: bold;\">R</span> <span style=\"text-align:left; color:#F4600A; font-size:11px;font-weight: bold;\">02.57</span> </span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:68%; left:79%;width:11%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"h9r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">7</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:45%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"h10l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:43%; left:55%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"h10r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight:bold;\">8</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:20%; left:80%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"h11l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Sa<span style=\"text-align:left; color:#F4600A; font-size:12px;font-weight: bold;\"></span> <span style=\"text-align:left; color:#F4600A; font-size:11px;font-weight: bold;\">03.03</span> </span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:19%; left:79%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"h11r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">9</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:3%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"h12l1\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:13%; left:73%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"h12r\" style = \"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">10</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("</div>");
        TBL.Append("</td>");

        TBL.Append("</tr>");
        TBL.Append("</table>");


        TBL.Append("<span>");
        TBL.Append("<table style = \"width:100%;border-collapse: collapse;font-family: 'Roboto', sans-serif;font-size:13px;margin-bottom:.65cm;-webkit-print-color-adjust: exact;\" >");
        TBL.Append("<tr>");
        TBL.Append("<td colspan = \"2\" style = \"text-align:left;padding:.30cm 0; \">");
        TBL.Append("<div style = \"font-size: 20px;font-weight:bold;color:#f25e0a;\" > Other Charts</div>");
        TBL.Append("</td>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
        TBL.Append("<td style = \"width:464px;\">");
        TBL.Append("<div style = \"color:Black;font-size:14px;font-weight:bold;\"> D09(Pros & amp; Cons of Married Life, Strength of Planets)</div >");
        
        TBL.Append("<div style = \"text-align: center;background:url("+ ChartImagePath  + ") no-repeat;background-position: center;background-size: 100% 100%;-webkit-print-color-adjust: exact;position: relative;z-index: 1;display: block;width:418px;padding-top: 100%; \">");
        TBL.Append("<div style=\"position:absolute; top:20%;  left:40%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh1l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"> Asc</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:38%;  left:46%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"fh1r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">10</span><br></span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top: 3%;  left: 14%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"fh2l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top: 14%;  left: 21%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh2r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">11</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:20%; left:2%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh3l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:19%; left:15%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh3r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">12</span><br></span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:42%; left:15%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh4l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ju Ve Sa Ra</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:44%; left:40%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh4r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">1</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:70%; left:2%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh5l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Su</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:68%; left:15%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"fh5r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">2</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:87%; left:14%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh6l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:74%; left:21%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh6r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">3</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:70%; left:40%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh7l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:49%; left:45%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh7r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">4</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:87%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh8l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Gk</span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:75%; left:70%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh8r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">5</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:67%; left:85%;width:15%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"fh9l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Mo</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:68%; left:75%;width:11%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"fh9r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">6</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:45%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"fh10l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ma Me Ke</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:44%; left:52%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"fh10r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">7</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:20%; left:80%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"fh11l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:19%; left:76%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"fh11r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">8</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:3%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh12l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:14%; left:70%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"fh12r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">9</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("</div>");
        TBL.Append("</td>");

        TBL.Append("<td style =\"width:464px;\">");
        TBL.Append("<div style=\"color:Black;font-size:14px;font-weight:bold;\">D10(Power & Position)</div>");
        TBL.Append("<div style = \"text-align: center;background:url(" + ChartImagePath + ") no-repeat;background-position: center;background-size: 100% 100%;-webkit-print-color-adjust: exact;position: relative;z-index: 1;display: block;width:418px;padding-top: 100%; \">");
        //TBL.Append("<div style = \"text-align: center;background:url(img/bgastrology.jpg) no-repeat;background-position: center;background-size: 100% 100%;-webkit-print-color-adjust: exact;position: relative;z-index: 1;display: block;width:464px;height:466px;padding-top: 100%;\">");
        TBL.Append("<div style=\"position:absolute; top:20%;  left:40%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id =\"sh1l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ju Asc</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:38%;  left:46%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh1r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">2</span><br></span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top: 3%;  left: 14%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh2l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top: 14%;  left: 21%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh2r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">3</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:20%; left:2%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh3l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:19%; left:15%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh3r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">4</span><br></span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:42%; left:15%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh4l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ve Ra</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:44%; left:40%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh4r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">5</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:70%; left:2%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh5l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Su</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:68%; left:15%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh5r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">6</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:87%; left:14%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh6l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Mo Me</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:74%; left:21%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh6r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">7</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:70%; left:40%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh7l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:49%; left:45%;width:10%;\"> ");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh7r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">8</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:87%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh8l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:75%; left:70%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh8r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">9</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:67%; left:85%;width:15%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh9l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Sa Gk</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:68%; left:75%;width:11%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh9r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">10</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:45%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh10l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ma Ke</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:44%; left:52%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh10r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">11</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:20%; left:80%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh11l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:19%; left:76%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh11r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">12</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:3%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh12l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:14%; left:70%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"sh12r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">1</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("</div>");
        TBL.Append("</td>");
        TBL.Append("</tr>");
        TBL.Append("<tr>");
       /******* start *********/
        TBL.Append("<td style = \"width:464px;\" >");
        TBL.Append("<div style=\"color:Black;font-size:14px;font-weight:bold;margin-top:.65cm;\">D24(Scholarly & Academic status)</div>");
        TBL.Append("<div style = \"text-align: center;background:url(" + ChartImagePath + ") no-repeat;background-position: center;background-size: 100% 100%;-webkit-print-color-adjust: exact;position: relative;z-index: 1;display: block;width:418px;padding-top: 100%; \">");
        TBL.Append("<div style=\"position:absolute; top:20%;  left:40%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh1l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"> Asc</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:38%;  left:46%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh1r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">7</span><br></span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top: 3%;  left: 14%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh2l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top: 14%;  left: 21%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh2r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">8</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:20%; left:2%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh3l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ma Ke</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:19%; left:15%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh3r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">9</span><br></span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:42%; left:15%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh4l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ve</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:44%; left:40%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh4r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">10</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:70%; left:2%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh5l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Su</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:68%; left:15%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh5r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">11</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:87%; left:14%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh6l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Me</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:74%; left:21%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh6r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">12</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:70%; left:40%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh7l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Mo</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:49%; left:45%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh7r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">1</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:87%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh8l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ju</span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:75%; left:70%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh8r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">2</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:67%; left:85%;width:15%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh9l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Sa Ra</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:68%; left:75%;width:11%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh9r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">3</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:45%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh10l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:44%; left:52%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh10r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">4</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:20%; left:80%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh11l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:19%; left:76%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh11r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">5</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:3%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh12l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Gk</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:14%; left:70%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh12r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">6</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("</div>");
        TBL.Append("</td>");
       /**********END****************/

        TBL.Append("<td style = \"padding:.0cm;vertical-align:top;width:425px;\" >");
        TBL.Append("<div style=\"color:Black;font-size:14px;font-weight:bold;margin-top:.65cm;\">D60(General Indicative & Shubhatwa & else)</div>");
        TBL.Append("<div style = \"text-align: center;background:url(" + ChartImagePath + ") no-repeat;background-position: center;background-size: 100% 100%;-webkit-print-color-adjust: exact;position: relative;z-index: 1;display: block;width:418px;padding-top: 100%; \">");
        //TBL.Append("<div style = \"text-align: center;background:url(img/bgastrology.jpg) no-repeat;background-position: center;background-size: 100% 100%;-webkit-print-color-adjust: exact;position: relative;z-index: 1;display: block;width:464px;height:466px;padding-top: 100%; \">");
        TBL.Append("<div style=\"position:absolute; top:20%;  left:40%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh1l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"> Asc</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:38%;  left:46%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh1r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">7</span><br></span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top: 3%;  left: 14%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh2l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top: 14%;  left: 21%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh2r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">8</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:20%; left:2%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh3l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ma Ke</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:19%; left:15%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh3r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">9</span><br></span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:42%; left:15%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh4l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ve</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:44%; left:40%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh4r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">10</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:70%; left:2%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh5l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Su</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:68%; left:15%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh5r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">11</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:87%; left:14%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh6l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Me</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:74%; left:21%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh6r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">12</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:70%; left:40%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh7l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Mo</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:49%; left:45%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh7r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">1</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:87%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh8l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Ju</span></span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:75%; left:70%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh8r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">2</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:67%; left:85%;width:15%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh9l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Sa Ra</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:68%; left:75%;width:11%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh9r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">3</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:45%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh10l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:44%; left:52%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh10r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">4</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:20%; left:80%;width:20%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh11l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:19%; left:76%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh11r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">5</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:3%; left:65%;width:30%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh12l1\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\">Gk</span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("<div style=\"position:absolute; top:14%; left:70%;width:10%;\">");
        TBL.Append("<span>");
        TBL.Append("<span id = \"frh12r\" style=\"text-align:left; color:#403E3E; font-size:12px;font-weight: bold;\"><br><span style=\"text-align:left; color:#6461CA; font-size:11px;font-weight: bold;\">6</span><br></span>");
        TBL.Append("</span>");
        TBL.Append("</div>");
        TBL.Append("</div>");
        TBL.Append("</td>");
        TBL.Append("</tr>");
        TBL.Append("</table>");


        TBL.Append("<div style = \"font-size:13px;\">");
        TBL.Append("<div style = \"font-size:18px;font-weight:bold;color:#f25e0a;\">Your Astro Report</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> You feel good when people share identical views as of yours on any matter, especially things which are of unusual and significant nature. On the contrary, if they give opposite views, you may get angry and furious and defy them.You need be much flexible during such times.</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> Your birth chart confirms that you may be in a habit of repeating the events, experiences and achievements which may make people more irritated who are arouund you. So, it is better and advised not to do so much freequenlty.</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> You are never averse to experience any new, unique and ground - breaking things, new techniques, new devices or gadget to use which improves your mental working, satisfaction, joy, learning and comforts in life to perform well.</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> You star confirms that you wish to be in a peaceful and noise free environment as more noise irritates you and lowers your productivity.So you must try to be in a much calm working environment to have higher productivity.</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> The supernatural and mysterious things do attract you to go deep to understand and practice them.</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> You shall be able to understand, sense and unveil any plotting, framing, mischievous scheme by people or public towards you or for your family members.You must be ready to face and counter such situations.</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> Your birth chart reveals that you are always in the process of thinking about a golden future for yourself be it for money, wealth, fame, studies or anything else and you work all out to achieve so without any sluggish and lazy moods.</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> If you have to do anything in a verbatim and replicated mode, you get irritated and starts disliking the work after some time and leave that . So other way you always enjoy any any work where the use of intellect and brain is higher and constantly.</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> One of the worst thing which makes your moods off is when you have to maintain a time sheet or complete a task in a fixed timeframe, do something in a scheduled manner etc.You may not like to continue for a long in such bounded way and look forward to become independent and enjoy liberty to complete the task.</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> No doubt you also like to do joking and kidding with people, friends, kids and so on but only when you are comfortable with them, otherwise you prefer to keep silent and remain in your moods.</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> Mercury will reflect the part of your creativity and your intelligence in life.Whether you will be able to manifest the divine force is also controlled by Mercury.Your management abilities, speculation activities and applying your mental faculties in earning big money or lose money in speculative activities also regulated by Mercury.Whether you will be able to get happiness from your children or not is reflected by Mercury.Mercury also controls your artistic talents.How good your intuitive power will work and how will you be able to achieve the new opportunities in life also shall be managed by Mercury.Your judgemental power to do right or wrong.Mercury will be controlling your intelligence and your capacity to think any original idea to translate into the reality astutely.How correctly you will be able to grasp various things and re - iterate things for other.How right you will be handling taxes and be a dominant authority in the area of execution of new initiatives.How will be your relations with your beloved other than your wife is indicated by Mercury ?</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> Mercury is controlling your education of higher level, your creative moods and your innovative mind faculties.How will be your period during when you are in a romantic relationship before getting married to your spouse.Mercury will also speak about your beloved which is other than your spouse.Whether you earn through speculation or not is also controlled by Mercury.How the original ideas will manifest in your life and turn into reality is also executed by Mercury.Will you be able to have deep learning about things ? Moreover, will you be able to re - iterate Mercury is controlling them ? Mercury reflects your spiritual attainment and religious activities to some extent backed by your inherent power.Chances of the conception of a child, having children, support and joy from children or pains from children also to be controlled by Mercury.Mercury dominates your literary composition and innovative moods.Whether your father is likely to go for long journeys related to personal, spiritual and professional work is what Mercury indicates.</div>");
        TBL.Append("<div style = \"margin-top:10px;\"> Venus is the lord of your fortune and good luck.Venus will uncover the amount and wealth of inheritance from your parents and ancestors property.How shall be your relations with your wife's siblings? Your belief in religious activities and spiritual matters is what Venus will reveal. How fruitful your travelling will be for personal and business-related trips. How shall be your relations with your foreign trips and your rapport with foreigners? Venus will gradually reveal, whether you will leave worldly life and later move on the high path in life or not. Venus will discover your relations with your Mentor, Gurus, teachers and another elder in your life. Whether you will have divine bliss is what Venus will reveal. How will be your grandchildren, and your connection with them shall be undiscovered by Venus.</div>");
        TBL.Append("</div>");

        TBL.Append("<div style = \"font-size:13px;margin-top:20px;\">");
        TBL.Append("<div style = \"font-size:16px;font-weight:bold;color:#333;\" > Category Lagna Predictive </div>");
        TBL.Append("<div style = \"margin-top:10px;\" > Very Wealthy and Famous </div>");
        TBL.Append("<div style = \"margin-top:10px;\" > Person will rise to new heights in his lifetime, enjoys all Comforts of life.</div>");
        TBL.Append("<div style = \"margin-top:10px;\" > Fickle minded but rich and have less maternal happiness </div>");
        TBL.Append("<div style = \"margin-top:10px;\" > Famous, Courageous natured native </div>");
        TBL.Append("<div style = \"margin-top:10px;\" > Likely to have Extra - Marital Affairs and Sensual life - Check aspect of Jupiter on 7th lord / 7th house / Venus / Mars for Savior / Protection </div>");
        TBL.Append("<div style = \"margin-top:10px;\" > Exponent in Civil Rights Laws.</div>");
        TBL.Append("<div style = \"margin-top:10px;\" > Expenditure for good cause.Wasteful expenditure also.</div>");
        TBL.Append("<div style = \"margin-top:10px;\" > No Evil will affect the native as the positive planers helps the native </div>");
        TBL.Append("<div style = \"margin-top:10px;\" > No Evil will affect the native as the positive planers helps the native in childhood </div>");
        TBL.Append("<div style = \"margin-top:10px;\" > Break in Education is indicated.</div>");
        TBL.Append("<div style = \"margin-top:10px;\" > Early start in Job is indicated</div>");
        TBL.Append("<div style = \"margin -top:10px;\" > You chart confirms that you will be intelligent enough to handle things, You will surely be liberal towards things and persons working with you and for you.You are fortunate enough to enjoy luxuries and comforts.You will be able to enjoy the honour from people Having many friends who will always be supportive for you does gets confirmed from Your Birth Chart. You will be able to amass wealth and property You may develop rheumatic disease.Also the possibility of  some kind of blood related problem exists. Advisors, Head of Institution, Business in Minerals are also possible e </ div > ");
        TBL.Append("</div>");
        TBL.Append("</div>");
        TBL.Append("</section>");








        divshowreport.InnerHtml = TBL.ToString();
        string reportHtml = TBL.ToString();
        var margins = new PageMargins
        {
            Top = 2,
            Bottom = 2,
            Left = 2,
            Right = 2
        };
        HtmlToPdfConverter _htmlToPdf = new HtmlToPdfConverter
        {
            Orientation = PageOrientation.Portrait,
            Margins = margins,
        };
        string folderPath = Server.MapPath("~/Image/");
        var FileName = "AstroReport_" + "sd" + "_" + DateTime.Now.ToString("ddMMyyyyHHss") + ".pdf";
        var pdfBytes = _htmlToPdf.GeneratePdf(reportHtml);
        var FolderWithFile = folderPath + FileName;
        System.IO.File.WriteAllBytes(FolderWithFile, pdfBytes);
        string DownLoadFileName = "~/Image/" + FileName;
        DownLoadFileName = DownLoadFileName.Replace("~", "");
        Response.ContentType = "application/pdf";
        Response.ContentEncoding = System.Text.Encoding.UTF8;
        Response.AddHeader("Content-Disposition", "attachment; filename=" + FileName + "");
        Response.BinaryWrite(pdfBytes);
        System.IO.File.WriteAllBytes(Server.MapPath("~/Image/") + FileName, pdfBytes);
        Response.Flush();
        Response.End();

    }

}