using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

public partial class Topbarnew_n : System.Web.UI.UserControl
{
    protected void Page_Load(object sender, EventArgs e)
    {
        //    if (Session["compcode"] == null)
        //    {
        //        Response.Write("<script>alert('Your Session Has Been Expired');window.close();</script>");
        //        return;
        //    }
        //    DataSet dsenablelink = new DataSet();
        //    dsenablelink.ReadXml(Server.MapPath("xml/topbarlink.xml"));
        //    if (Session["comp_name"] != null)
        //    {
        //        hidcompname.Value = Session["comp_name"].ToString();
        //    }
        //    if (Session["center"] != null)
        //    {
        //        hidcenter.Value = Session["center"].ToString();
        //    }
        //    if (Session["Username"] != null)
        //        hidusername.Value = Session["username"].ToString();
        //    if (Session["userid"] != null)
        //        hiduserid.Value = Session["userid"].ToString();
        //    if (Session["compcode"] != null)
        //        hidcompcode.Value = Session["compcode"].ToString();
        //    if (Session["dateformat"] != null)
        //        hidauto.Value = Session["dateformat"].ToString();
        //    if (Session["autogenerated"] != null)
        //        hidautogenerated.Value = Session["autogenerated"].ToString();
        //    if (Session["center"] != null)
        //        hiddencenter.Value = Session["center"].ToString();
        //    if (Session["revenue"] != null)
        //        hiddenreveneue.Value = Session["revenue"].ToString();

        //    if (Session["centername"] != null)
        //        hidunitname.Value = Session["centername"].ToString();

        //    imglogo.Src = "Images/" + ConfigurationManager.AppSettings["logoimg"].ToString();
        //    imglogo.Width = Convert.ToInt32(ConfigurationManager.AppSettings["logoimgwidth"].ToString());

        //    string center = ConfigurationSettings.AppSettings["center"].ToString();
        //     if (center == "depo")
        //    {
        //    if (System.IO.Path.GetFileName(Page.Request.PhysicalPath) != "cngpassword.aspx")
        //    {
        //        DataSet ds=new DataSet();
        //        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        //            {
        //                NewAdbooking.Classes.login tab = new NewAdbooking.Classes.login();
        //                ds = tab.getmoduleper(hidcompcode.Value, hiduserid.Value);
        //            }
        //            else if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        //            {
        //                NewAdbooking.classesoracle.login tab = new NewAdbooking.classesoracle.login();
        //                ds = tab.getmoduleper(hidcompcode.Value, hiduserid.Value);
        //            }
        //            else
        //            {
        //                NewAdbooking.classesoracle.login tab = new NewAdbooking.classesoracle.login();
        //                ds = tab.getmoduleper(hidcompcode.Value, hiduserid.Value);
        //            }
        //           string adaccount="0";
        //           string layoutx = "0";
        //           string cir = "0";
        //           string pam = "0";
        //           string news = "0";
        //           string pay = "0";
        //           string finance = "0";
        //           string dashboard = "0";
        //           for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
        //           {
        //               if (ds.Tables[0].Rows[i].ItemArray[0].ToString() == "ADA")
        //                   adaccount = "1";
        //               else if (ds.Tables[0].Rows[i].ItemArray[0].ToString() == "LAY")
        //                   layoutx = "1";
        //               else if (ds.Tables[0].Rows[i].ItemArray[0].ToString() == "CIR")
        //                   cir = "1";
        //               else if (ds.Tables[0].Rows[i].ItemArray[0].ToString() == "PAM")
        //                   pam = "1";
        //               else if (ds.Tables[0].Rows[i].ItemArray[0].ToString() == "NEW")
        //                   news = "1";
        //               else if (ds.Tables[0].Rows[i].ItemArray[0].ToString() == "PAY")
        //                   pay = "1";
        //               else if (ds.Tables[0].Rows[i].ItemArray[0].ToString() == "FIN")
        //                   finance = "1";
        //               else if (ds.Tables[0].Rows[i].ItemArray[0].ToString() == "DASH")
        //                   dashboard = "1";
        //           }

        //       /* if (dsenablelink.Tables[0].Rows[0].ItemArray[0].ToString() == "enable")
        //        {
        //            lbldisplay.Visible = true;

        //        }
        //        else
        //        {
        //            lbldisplay.Visible = false;
        //        }
        //        if (dsenablelink.Tables[0].Rows[0].ItemArray[1].ToString() == "enable")// for classified booking
        //        {
        //            Label2.Visible = true;

        //        }
        //        else
        //        {
        //            Label2.Visible = false;
        //        }
        //        if (dsenablelink.Tables[0].Rows[0].ItemArray[2].ToString() == "enable")/// for layoutx
        //        {
        //            Label3.Visible = true;
        //        }
        //        else
        //        {
        //            Label3.Visible = false;
        //        }
        //        if (dsenablelink.Tables[0].Rows[0].ItemArray[3].ToString() == "enable")// for News-Wrap
        //        {
        //            Label4.Visible = true;
        //        }
        //        else
        //        {
        //            Label4.Visible = false;
        //        }
        //        if (dsenablelink.Tables[0].Rows[0].ItemArray[4].ToString() == "enable")// 4C-DAMS
        //        {
        //            Label5.Visible = true;
        //        }
        //        else
        //        {
        //            Label5.Visible = false;
        //        }
        //        if (dsenablelink.Tables[0].Rows[0].ItemArray[5].ToString() == "enable")// QBC
        //        {
        //            Label9.Visible = true;
        //        }
        //        else
        //        {
        //            Label9.Visible = false;
        //        }
        //        if (dsenablelink.Tables[0].Rows[0].ItemArray[6].ToString() == "enable")// circculation
        //        {
        //            lblcir.Visible = true;
        //        }
        //        else
        //        {
        //            lblcir.Visible = false;
        //        }
        //        if (dsenablelink.Tables[0].Rows[0].ItemArray[7].ToString() == "enable")// Ad-Accounts
        //        {
        //            Label1.Visible = true;
        //        }
        //        else
        //        {
        //            Label1.Visible = false;
        //        }*/

        //       if (dsenablelink.Tables[0].Rows[0].ItemArray[0].ToString() == "enable" && dashboard == "1")
        //       {
        //           lbldashboard.Visible = true;

        //       }
        //       else
        //       {
        //           lbldashboard.Visible = false;
        //       }

        //        if (dsenablelink.Tables[0].Rows[0].ItemArray[0].ToString() == "enable" && adaccount=="1")
        //        {
        //            lbladaccount.Visible = true;

        //        }
        //        else
        //        {
        //            lbladaccount.Visible = false;
        //        }
        //           if (dsenablelink.Tables[0].Rows[0].ItemArray[1].ToString() == "enable" && layoutx=="1")
        //        {
        //            lbllayoutx.Visible = true;

        //        }
        //        else
        //        {
        //            lbllayoutx.Visible = false;
        //        }
        //           if (dsenablelink.Tables[0].Rows[0].ItemArray[2].ToString() == "enable" && cir=="1")
        //        {
        //            lblcir.Visible = true;
        //        }
        //        else
        //        {
        //            lblcir.Visible = false;
        //        }
        //           if (dsenablelink.Tables[0].Rows[0].ItemArray[3].ToString() == "enable" && pam=="1")
        //        {
        //            lblpam.Visible = true;
        //        }
        //        else
        //        {
        //            lblpam.Visible = false;
        //        }
        //           if (dsenablelink.Tables[0].Rows[0].ItemArray[4].ToString() == "enable" && news=="1")
        //        {
        //            lblnews.Visible = true;
        //        }
        //        else
        //        {
        //            lblnews.Visible = false;
        //        }
        //           if (dsenablelink.Tables[0].Rows[0].ItemArray[5].ToString() == "enable" && pay=="1")
        //        {
        //            lblpayroll.Visible = true;
        //        }
        //        else
        //        {
        //            lblpayroll.Visible = false;
        //        }
        //           if (dsenablelink.Tables[0].Rows[0].ItemArray[6].ToString() == "enable" && finance=="1")
        //        {
        //            lblfinance.Visible = true;
        //        }
        //        else
        //        {
        //            lblfinance.Visible = false;
        //        }

        //    }
        //    else
        //    {
        //        lbladaccount.Visible = false;
        //        lbllayoutx.Visible = false;
        //        lblcir.Visible = false;
        //        lblpam.Visible = false;
        //        lblnews.Visible = false;
        //        lblpayroll.Visible = false;
        //        lblfinance.Visible = false;
        //    }

        //    if (System.IO.Path.GetFileName(Page.Request.PhysicalPath) != "Default.aspx")
        //    {
        //        _lbuser.Attributes.Add("style", "display:none");
        //        _user.Attributes.Add("style", "display:none");
        //        _lbcom.Attributes.Add("style", "display:none");
        //        _com.Attributes.Add("style", "display:none");
        //        _lbadmin.Attributes.Add("style", "display:none");
        //        _admin.Attributes.Add("style", "display:none");
        //    }
        //    saveLoginInfo(Session["compcode"].ToString(), Session["userid"].ToString(), "");
        //    DataSet ds = new DataSet();
        //    ds.ReadXml(Server.MapPath("XML/releaseno.xml"));
        //    lbrelease.Text = ds.Tables[0].Rows[0].ItemArray[0].ToString();
        //    //}


        //}

        //public void saveLoginInfo(string compcode, string userid, string ip)
        //{
        //    if (Session["SESSIONID"] != null)
        //    {
        //        if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "sql")
        //        {
        //            NewAdbooking.Classes.login logindetail = new NewAdbooking.Classes.login();
        //            logindetail.saveLoginInfo(compcode, userid, ip, "UPDATE", Session["SESSIONID"].ToString());
        //        }
        //        else
        //            if (ConfigurationSettings.AppSettings["ConnectionType"].ToString() == "orcl")
        //            {
        //                NewAdbooking.classesoracle.login logindetail = new NewAdbooking.classesoracle.login();
        //                logindetail.saveLoginInfo(compcode, userid, ip, "UPDATE", Session["SESSIONID"].ToString());
        //            }
        //    }

       
    }
}