using System;
using System.Collections;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Xml.Linq;

public partial class topbarnew : System.Web.UI.UserControl
{
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["Username"] != null)
            hidusername.Value = Session["username"].ToString();
        if (Session["userid"] != null)
            hiduserid.Value = Session["userid"].ToString();
        if (Session["compcode"] != null)
            hidcompcode.Value = Session["compcode"].ToString();
        if (Session["dateformat"] != null)
            hidauto.Value = Session["dateformat"].ToString();
        if (Session["autogenerated"] != null)
            hidautogenerated.Value = Session["autogenerated"].ToString();
    }
}
