function chkadmin() {
    if (document.getElementById('services') != null) {
        if (document.getElementById('hiddenadmin').value == "yes") {
            document.getElementById('services').style.display = "block";


        }
        else {
            document.getElementById('services').style.display = "none";
        }
    }

    var username = document.getElementById('hiddenusername').value;
    var compuser = document.getElementById('hiddencompuser').value;
    var admin = document.getElementById('hiddenadmin').value;
    if (compuser == "Agency" && admin == "yes") {
        comp_ = "Agency";
        admin_ = "Admin";
    }
    else if (admin == "yes" && compuser != "Agency") {
        comp_ = "Hindustan";
        admin_ = "Admin";
    }
    else if (compuser == "Agency" && admin != "yes") {
        comp_ = "Agency";
        admin_ = "User";

    }
    else if (compuser != "Agency" && admin != "yes") {
        comp_ = "Hindustan";
        admin_ = "User";

    }
    //	document.getElementById("_user").innerHTML=username;
    //	document.getElementById("_com").innerHTML=" @ "+comp_;
    //	document.getElementById("_admin").innerHTML="( "+admin_+" )" ;


}


var flag = 0;
function openlayout() {
    window.open("http://lata/layoutx/default.aspx?auto=" + document.getElementById('Topbar1$hidautogenerated').value + "&Username=" + document.getElementById('Topbar1$hidusername').value + "&userid=" + document.getElementById('Topbar1$hiduserid').value + "&compcode=" + document.getElementById('Topbar1$hidcompcode').value + "&dateformat=" + document.getElementById('Topbar1$hidauto').value + "");
}

function toggle(node) {





    var nextDIV = node.nextSibling;

    // find the next DIV








    while (nextDIV.nodeName != "DIV") {

        nextDIV = nextDIV.nextSibling;
        //alert(nextDIV.nodeName);




    }

    // Unfold the branch if it isn't visible

    if (nextDIV.style.display == 'none') {
        // Change the image (if there is an image)
        if (node.childNodes.length > 0) {


            var i;
            for (i = 0; i < node.childNodes.length; i++) {

                //alert(node.childNodes.length);
                if (node.childNodes.item(i).nodeName == "IMG") {

                    //alert(node.childNodes.item(0).nodeName);
                    node.childNodes.item(i).src = getImgDirectory(node.childNodes.item(i).src) + "minus.gif";

                }

            }


        }
        nextDIV.style.display = 'block';


    }

    // Collapse the branch if it IS visible

    else {



        // Change the image (if there is an image)

        if (node.childNodes.length > 0)

            var i;
        for (i = 0; i < node.childNodes.length; i++) {
            {

                if (node.childNodes.item(i).nodeName == "IMG") {

                    node.childNodes.item(i).src = getImgDirectory(node.childNodes.item(i).src) + "plus.gif";

                }

            }
        }


        nextDIV.style.display = 'none';


    }


    //alert(document.getElementById('group'+i).style.display);





}

function getImgDirectory(source) {
    //alert(source.substring(0, source.lastIndexOf('/') + 1));
    return source.substring(0, source.lastIndexOf('/') + 1);

}


var z = "0";
var x = "";
var status = "";
function toggle1(node, a) {
    var rep = a.length;
    var rep1 = a.substring(rep, rep - 1);

    if (z == "1") {
        document.getElementById('group' + x).style.display = "none";
        status = "none";
        z = 0;

    }
    for (var i = 1; i <= 2; i++) {

        //document.getElementById('group'+rep1).style.display="none";
        if ("group" + i == "group" + rep1) {
            if (document.getElementById('group' + rep1).style.display == "none") {
                document.getElementById('group' + rep1).style.display = "block";
            }
            else if (document.getElementById('group' + rep1).style.display == "block") {
                document.getElementById('group' + rep1).style.display = "none";
            }
            else {
                document.getElementById('group' + rep1).style.display = "block";
                status = "block";
                //z="1";
                x = rep1;
                //alert("second if loop"+status);
            }
        }
        else {
            if ("group" + i != "group" + rep1) {
                document.getElementById('group' + i).style.display = "none";
                //document.getElementById('group'+rep1).style.display="block";
                //
                status = "none";

                //alert("third if loop"+status)
            }
            else if (document.getElementById('group' + i).style.display = "block") {
                document.getElementById('group' + i).style.display = "none"
            }
        }
    }

    /*if(document.getElementById('group'+rep1).style.display=="block")
    {
    if (node.childNodes.item(rep1).nodeName == "IMG" || node.childNodes.item(rep1).nodeName == "#text") 
    {
				
    node.childNodes.item(rep1).src = getImgDirectory(node.childNodes.item(rep1).src) + "minus.gif";

			}
		
		}
		
		if(document.getElementById('group'+rep1).style.display=="none")
    {
    if (node.childNodes.item(rep1).nodeName == "IMG" || node.childNodes.item(rep1).nodeName == "#text") 
    {
				
    node.childNodes.item(rep1).src = getImgDirectory(node.childNodes.item(rep1).src) + "plus.gif";

			}
		
		}*/

}

//function datesave()
//{

//var compcode=document.getElementById('hiddencode').value;
//var userid=document.getElementById('hiddenuserid').value;
//var dateformat=document.getElementById('drpdateformat').value;
//var code=document.getElementById('drpcodetype').value;
//var curr=document.getElementById('drpcurr').value;
//var ratecode=document.getElementById('drprategroup').value;
//date.updatedate(compcode,userid,dateformat,code,curr,ratecode);


//alert("Your Date Update Sucessfuly");

//return false;

//}


function abc() {

    var userid = document.getElementById('hiddenuserid').value;
    var compcode = document.getElementById('hiddencompcode').value;

    //EnterPage.submitpermission(compcode,userid,'Agent_Master',call_agency);
    ClientMaster.submitpermission(compcode, userid, 'Agent_Master', call_agency);
    return false;

}

function call_agency(response) {
    var ds = response.value;

    if (ds.Tables[0].Rows[0].button_id == "0" || ds.Tables[0].Rows[0].button_id == "8") {
        alert("You Are Not Authorised To See This Form");
        return false;

    }
    else {
        window.location.href = 'agent_master.aspx';
        return false;
    }


}



function FormPermission(formname, name) {

    //alert("hitree");
    //alert(parent.document.getElementById('td1'));
    //parent.document.getElementById('td1').innerHTML="<div class=FormLabel id=Formname nowrap>"+name+"</div>";
    var userid = document.getElementById('hiddenuserid').value;
    var compcode = document.getElementById('hiddencompcode').value;
    window.open('UOM.aspx?empcode=HT001&userid=A01&formname=ClientMaster.aspx&index=1');

    //ClientMaster.submitpermission(compcode,userid,formname,form_CallBack);
    return false;

}

function FormPermissionexec(formname) {

    var userid = document.getElementById('hiddenuserid').value;
    var compcode = document.getElementById('hiddencompcode').value;

    ClientMaster.submitpermission(compcode, userid, formname, form_CallBack);
    return false;

}

function FormPermissionagency(formname) {

    var userid = document.getElementById('hiddenuserid').value;
    var compcode = document.getElementById('hiddencompcode').value;

    ClientMaster.submitpermission(compcode, userid, formname, form_CallBack);
    return false;

}





function form_CallBack(response) {
    var ds = response.value;
    if (ds.Tables[0].Rows[0].button_id == 0) {
        alert("You Are Not Authorised To See This Form");
        return false;

    }
    else {
        //alert(document.getElementById("detail"));
        //window.location.href=''+ds.Tables[0].Rows[0].form_name+'.aspx' ;

        //document.getElementById("detail").src=''+ds.Tables[0].Rows[0].form_name+'.aspx';
        //window.open(''+ds.Tables[0].Rows[0].form_name+'.aspx');

        for (var index = 0; index < 200; index++) {


            popUpWin2
     = window.open('' + ds.Tables[0].Rows[0].form_name + '.aspx');
            popUpWin2.focus();
            return false;
        }



        return false;
    }
}

function home(formname) {
    document.getElementById("detail").src = 'EnterPage.aspx';
    parent.document.getElementById('td1').innerHTML = "<div class=FormLabel id=Formname nowrap>" + formname + "</div>";
    return false;

}

function logout() {

    window.location.href = 'logout.aspx';

    return false;
}
function openChange_Pwd() {
    // document.getElementById("detail").src="cngpassword.aspx";
    window.open('cngpassword.aspx', '', 'width=' + screen.availWidth + ',height=' + screen.availHeight + ',resizable=1,left=0,top=0,scrollbars=yes');

}
function masterprevilege() {
    //alert(document.getElementById('detail'));
    ///* change*/
    if (document.getElementById('hiddencompuser').value == "Agency" && document.getElementById('hiddenadmin').value == "yes") {
        var userid = document.getElementById('hiddenuserid').value;
        var compcode = document.getElementById('hiddencompcode').value;
        _Default.chkpermissionagency(userid, openservices_form);
    }
    else {
        document.getElementById("detail").src = "module_detail.aspx";
    }
    //window.location.href='module_detail.aspx';
    return false;

}
function openservices_form(res) {
    var ds = res.value;
    if (ds.Tables[0].Rows.length > 0) {
        document.getElementById("detail").src = "module_detail.aspx";
    }
    else {
        alert("Please set the permission");
    }
    return false;

}

function createuser() {
    //alert(document.getElementById('detail'));
    //document.getElementById("detail").src="Createuser.aspx";
    var userform;
    var formname = createuser;
    //		         if(userform && !userform.closed)
    //	            {
    //	            
    //	            //document.getElementById('closewin').value=handleform[i];
    //	             userform.focus();
    //	            //return false;
    //	            //count;
    //	            
    //	            }
    //	            else
    //	            {
    //win=window.open(''Createuser.aspx','','width='+screen.availWidth+',height='+screen.availHeight+',resizable=1,left=0,top=0,scrollbars=yes');
    window.open('Createuser.aspx', '', 'width=' + screen.availWidth + ',height=' + screen.availHeight + ',resizable=1,left=0,top=0,scrollbars=yes');

    //win=window.open(''+formname+'.aspx');


    //               
    //	             userform=win;
    //	             
    //	            //return false;
    //	            
    //	            }


    //window.location.href='module_detail.aspx';
    return false;

}

//		function date()
//		{
//		window.location.href='date.aspx';
//return false;
//		}

function date() {
    window.location.href = 'updateprefer.aspx';
    return false;
}






function logoutpage() {
    var c;
    //alert(typeof(formopen));


    //alert(win);
    if (typeof (win) != "undefined") {
        win.close();
    }
    window.location.href = "logout.aspx";
    window.close();

    return false;
}

function calldepo(formname) {
    //alert(parent.document.getElementById('td1').innerHTML);

    //parent.document.getElementById('td1').innerHTML="<div class=FormLabel id=Formname nowrap>"+formname+"</div>";
    var userid = document.getElementById('hiddenuserid').value;
    var compcode = document.getElementById('hiddencompcode').value;
    //document.getElementById("detail").src='DepotIncmaster.aspx';
    window.open('DepotIncmaster.aspx');



    return false;


}
function homekeeping() {
    var userid = document.getElementById('hiddenuserid').value;
    var compcode = document.getElementById('hiddencompcode').value;
    //var permision="P";

    _Default.givepermision(userid, compcode, 'P', calldeletion);
    return false;
}

function calldeletion(response) {
    var ds = response.value;
    if (ds.Tables[0].Rows[0].HOUSEKEEPING != "P") {
        alert("You Are Not Authorised To See This Form");
        return false;

    }
    else {
        window.location.href = 'deletion.aspx';
        return false;
    }


}
